name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    type: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      
